### PR TITLE
Add gradient evaluation for Fletcher-Powell

### PR DESCRIPTION
**Pull request by anriseth**

### CODE REVIEW

**Comment by pkofod** [comment]
hand-derived, look-up, or symbolic?

**Comment by anriseth** [comment]
It was lying around on one of my computers. Think I looked it up somewhere
last month...

**Comment by pkofod** [comment]
Ok :) do you have merge rights?

**Comment by anriseth** [comment]
> do you have merge rights?

Nope, can't see any merge buttons here :p

**Comment by pkofod** [comment]
now?

**Pull request merged**
