### PR TITLE
Update REQUIRE for femtocleaner

### PR DESCRIPTION
**Pull request by anriseth**

### CODE REVIEW

**Comment by anriseth** [comment]
Hmm, I'm not getting the femtocleaner option in "checks". @pkofod is femtocleaner enabled for this repo? I tried to add it now but there wasn't an option to do so.

**Comment by anriseth** [comment]
Ah, a JuliaNLSolvers administrator needs to update the permissions for femtocleaner https://github.com/apps/femtocleaner/installations/47776/permissions (I don't have access)

**Comment by pkofod** [comment]
looks like it's cleaning

**Comment by anriseth** [comment]
> looks like it's cleaning

:robot: <3

**Pull request merged**
